### ISSUE TITLE
I get this error when I start the bot

### ISSUE THREAD

**Issue by kjkimmm** [jongeunpark/node-steemit-randowhale-bot#1]
Error: getaddrinfo ENOTFOUND steemd.steemit.com steemd.steemit.com:443
    at errnoException (dns.js:55:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:26)

**Comment by jongeunpark** [comment]
I know. This issue is low steem.js version. You update version steem.js
